AWSTemplateFormatVersion: 2010-09-09
Resources:
  WordServiceExistenceProcessor:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: WordServiceExistenceProcessor
      Handler: WordServiceExistenceProcessor::WordServiceExistenceProcessor.Function::FunctionHandlerAsync
      Description: Check existence of a word
      Role:
        Fn::GetAtt:
          - PartyGamesLambdaRole
          - Arn
      Code:
        S3Bucket: party-games-functions
        S3Key: WordServiceExistenceProcessorCode
      Runtime: dotnetcore3.1

  UpdateWordRequestProcessor:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: UpdateWordRequestProcessor
      Handler: UpdateWordRequestProcessor::UpdateWordRequestProcessor.Function::FunctionHandlerAsync
      Description: Add or update a word in the WordTable
      Role:
        Fn::GetAtt:
          - PartyGamesLambdaRole
          - Arn
      Code:
        S3Bucket: party-games-functions
        S3Key: UpdateWordRequestProcessorCode
      Runtime: dotnetcore3.1

  WordTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: "Word"
          AttributeType: "S"
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 20
        WriteCapacityUnits: 20
      KeySchema:
        -
          AttributeName: "Word"
          KeyType: "HASH"
      TableName: "WordTable"
      
  CategoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Word"
          AttributeType: "S"
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      KeySchema:
        -
          AttributeName: "Word"
          KeyType: "HASH"
      TableName: "CategoryTable"

  PartyGamesLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: IAM role for the word service existence processor
      Path: /
      Policies:
        - PolicyName: AWSLambdaBasicExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
        - PolicyName: ReadWriteTable
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:BatchGetItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                  - 'dynamodb:BatchWriteItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                Resource: 
                  - 'arn:aws:dynamodb:*:*:table/WordTable'
                  - 'arn:aws:dynamodb:*:*:table/CategoryTable'
        - PolicyName: AmazonS3FullAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource:
                  - 'arn:aws:s3:::exchange-data-raw'
                  - 'arn:aws:s3:::Exchange-data-raw/*'